### ISSUE TITLE
Getting high CPU Usage

### ISSUE THREAD

**Issue by ra100** [wakatime/blender-wakatime#6]
For some projects (didn't find the pattern, yet),

after opening a project, wakatime cli jumps to 100% CPU on one thread and uses other 10+

I've tried to name file same way, as the one that behaves like this, but that works fine.

I'm not sure what I can do to debug this isssue.

---
Blender 3.6.4
Xubuntu 23.04
wakatime blender 2.0.1

**Comment by snick-m** [comment]
Hi, do you still notice the issue? Have you managed to replicate it on a different machine - say with the same project file? I'd love to figure this out with you.

**Comment by ra100** [comment]
Thanks, I didn't encounter it lately. If it would occur again, I'll try it on a different system and see.
So for now, I'm closing this.
